### ISSUE TITLE
Token 泄漏！建议研究一下下图的安全保存密钥的方法

### ISSUE THREAD

**Issue by Mrered** [ivaquero/homebrew-chinese#61]
https://github.com/ivaquero/homebrew-chinese/blob/515dbf46e332d69d9e13534b4f3c8b2d779e5e17/.github/workflows/main.yml#L44C28-L44C28

![image](https://github.com/ivaquero/homebrew-chinese/assets/34948506/df2ccf66-3204-4e29-be82-b9e73f2043cf)

**Comment by Mrered** [comment]
以下是 Bing 的建议：

在GitHub Actions中，你可以使用**secrets**来保存你的密钥。这是一个安全的方法，可以防止你的密钥在公开的yml文件中被暴露。以下是如何设置和使用secrets的步骤：

1. 在你的GitHub仓库中，点击"Settings"选项卡。
2. 在左侧的菜单中，点击"Secrets"。
3. 点击"New repository secret"按钮。
4. 在"Name"字段中输入你的密钥的名称，例如`MY_SECRET_KEY`。
5. 在"Value"字段中输入你的密钥的值。
6. 点击"Add secret"按钮。

现在，你的密钥已经安全地保存在你的仓库中了。你可以在你的GitHub Actions的yml文件中使用这个密钥，如下所示：

```yaml
steps:
  - name: My step
    env:
      MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
    run: |
      echo "My secret key is $MY_SECRET_KEY"
```

在这个例子中，`MY_SECRET_KEY`是你在GitHub Secrets中设置的密钥的名称。`${{ secrets.MY_SECRET_KEY }}`语法会在运行时将其替换为你在secrets中设置的实际值。这样，你的密钥就不会在你的yml文件中被暴露出来了。请注意，虽然你可以在运行时访问这个值，但是你不能在GitHub Actions的日志中打印这个值，因为GitHub会自动将其红蔽。

希望这个信息对你有所帮助！如果你还有其他问题，欢迎随时向我提问。😊
